/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ccard_thesis_Indoor_Localization_and_Guidance_JNI_Interface_LSH_Wrapper */

#ifndef _Included_ccard_thesis_Indoor_Localization_and_Guidance_JNI_Interface_LSH_Wrapper
#define _Included_ccard_thesis_Indoor_Localization_and_Guidance_JNI_Interface_LSH_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ccard_thesis_Indoor_Localization_and_Guidance_JNI_Interface_LSH_Wrapper
 * Method:    init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ccard_thesis_Indoor_1Localization_1and_1Guidance_JNI_1Interface_LSH_1Wrapper_init
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ccard_thesis_Indoor_Localization_and_Guidance_JNI_Interface_LSH_Wrapper
 * Method:    train
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ccard_thesis_Indoor_1Localization_1and_1Guidance_JNI_1Interface_LSH_1Wrapper_train
  (JNIEnv *, jobject);

/*
 * Class:     ccard_thesis_Indoor_Localization_and_Guidance_JNI_Interface_LSH_Wrapper
 * Method:    add
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ccard_thesis_Indoor_1Localization_1and_1Guidance_JNI_1Interface_LSH_1Wrapper_add
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ccard_thesis_Indoor_Localization_and_Guidance_JNI_Interface_LSH_Wrapper
 * Method:    knnMatch
 * Signature: (JIZ)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ccard_thesis_Indoor_1Localization_1and_1Guidance_JNI_1Interface_LSH_1Wrapper_knnMatch
  (JNIEnv *, jobject, jlong, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
